version: '3'
services:
  v2ray:
    restart: 'always'
    image: 'v2ray/official'
    container_name: 'v2ray'
    command: v2ray -config=/etc/v2ray/config_crt.json
    ports:
      - '0.0.0.0:12321:12321'
    volumes:
      - '/root/v2ray:/etc/v2ray'